/* Copyright 2014 lennart.borgman@gmail.com */ (function(){function v(a,b){if(!b)debugger;if(!b||!/^[0-9]+$/.exec(b))throw"Bad id '"+b+"' in ZURLBuilder";this.m=a;this.id=b}v.prototype.j="https://api.zotero.org/";v.prototype.h="?format\x3datom\x26content\x3djson";function G(a){return a.j+(a.m?"groups":"users")+"/"+a.id+"/"}v.prototype.item=function(a){if(!a)debugger;return G(this)+"items/"+a+this.h};function H(a,b){if(!b)debugger;return G(a)+"items/"+b}v.prototype.children=function(a){if(!a)debugger;return G(this)+"items/"+a+"/children"+this.h+"\x26order\x3ddateAdded\x26sort\x3dasc"};
function M(a,b,d,e,r,t){this.n=a;this.a=b;this.d=d;this.g=e;this.e=r;this.k=t;this.status={}}
M.prototype.onload=function(){debugger;console.log("prototype xhr callback ",this.b.status,this.b);if(4!==this.b.readyState){console.log("readyState",this.b.readyState);alert("wrong zreader onload function called");debugger}if(200<=this.b.status&&400>this.b.status){if(this.a)for(this.a.classList.remove("zreader-requested"),this.a.classList.add("zreader-received");this.a.firstChild;)this.a.removeChild(this.a.firstChild);var a=this.b.responseText;this.g&&this.g(a,this.a);this.d&&(a=N(a),this.d(a,this.a));
this.e&&this.e()}else console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+this.b.status.toString()),this.a&&(this.a.classList.remove("zreader-requested"),this.a.classList.add("zreader-error"),this.a.appendChild(Q("div",null,["Couldn't read the requested file",Q("br"),"STATUS \x3d "+this.b.status.toString()])))};function R(a){if(!a.b)a.b=U(a.n,a.a,a.d,a.g,a.e,a.k,a.status);else if(4===a.b.readyState)a.b.onload()}
function U(a,b,d,e,r,t,s){console.log("zRR",a,"statusObj",s);var c=b?b.dataset.c:void 0;s&&(c=s.status);switch(c){case void 0:s&&(s.status="requested");b&&(c=Q("div",{"class":"zreader-request-info"},"Fetching information from Zotero... (this might not work on mobiles due to a bug in Chrome)"),s||(b.dataset.c="requested",b.classList.remove("zreader-error"),b.classList.remove("zreader-received"),b.classList.add("zreader-requested")),b.appendChild(c));var p=new XMLHttpRequest;p.onerror=function(a){logIt(p.statusText);
logIt(a)};p.onload=function(){if(200<=p.status&&400>p.status){s&&(s.status="received");if(b)for(s||(b.dataset.c="received",b.classList.remove("zreader-requested"),b.classList.add("zreader-received"));b.firstChild;)b.removeChild(b.firstChild);var a=p.responseText;e&&e(a,b);d&&(a=N(a),d(a,b));r&&r()}else console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+p.status.toString()),s&&(s.status="failed"),b&&(s||(b.dataset.c="failed",b.classList.remove("zreader-requested"),b.classList.add("zreader-error")),
b.appendChild(Q("div",null,["Couldn't read the requested file",Q("br"),"status \x3d "+p.status.toString()])),t&&t())};p.ontimeout=function(){logIt("rq.ontimeout "+a)};p.onreadystatechange=function(){4===p.readyState&&200!==p.status&&console.log("Error",p.statusText)};p.open("GET",a,!0);try{p.send()}catch(g){logIt(g)}return p}}
function N(a){theJX=a;E=a=(new DOMParser).parseFromString(a,"text/xml").querySelectorAll("entry");for(var b=[],d=0;d<a.length;d++){var e=a[d],r=e.getElementsByTagNameNS("http://zotero.org/ns/api","key")[0].textContent,t=e.querySelector("published").textContent,e=e.querySelector("content").firstChild.nodeValue,e=JSON.parse(e);e.zoteroItemKey=r;e.zoteroPublished=t;b[d]=e}return J=b}
function Q(a,b,d){function e(a){"string"==typeof a?r.appendChild(document.createTextNode(a)):r.appendChild(a)}var r=document.createElement(a);if(d)if(d.length&&"string"!=typeof d)for(a=0;a<d.length;a++)d[a]&&e(d[a]);else e(d);for(var t in b)r.setAttribute(t,b[t]);return r}function X(a,b){var d=new XMLHttpRequest;d.open("get","http://ourcomments.org/cgi-bin/zlibdesc.php?zlib\x3d"+a,!0);d.onerror=function(a){logIt(rq.statusText);logIt(a)};d.onload=function(){b(d)};try{d.send()}catch(e){logIt(e)}}
function Y(a){for(var b="http://zotero.org/groups/"+php_zgi,d=void 0;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(Q("span",null,"Fetching info..."));a.style.display="block";X(b,function(e){for(;a.firstChild;)a.removeChild(a.firstChild);if(200<=e.status&&400>e.status){e=e.responseText;var r=Q("div");e=e.replace(/ src="[^h]/g,' xsrc\x3d"');r.innerHTML=e;e=r.querySelector("div.minor-col.last-col");for(var t=e.querySelector("ul.group-information"),s;s=t.nextSibling;)s.parentNode.removeChild(s);
t.parentNode.removeChild(t);t=e.querySelectorAll("a");s=0;for(var c;c=t[s++];){var p=c.getAttribute("href");"/"===p.substr(0,1)&&c.setAttribute("href","https://www.zotero.org"+p)}!d&&(d="(fix-me)",r=r.querySelector("[id\x3d'group-show'] h1"))&&(d=r.innerText,r.parentNode.removeChild(r));r=Q("div",{"class":"libinfo-header",title:"Visit Zotero"},["Zotero library ",Q("a",{href:b},d)]);a.appendChild(r);a.appendChild(e)}else a.innerHTML="Could not get info. Please right click on link.",console.log("Couldn't read the requested file, status \x3d "+
e.status.toString())})};ZReaderRefCopier={l:function(a){var b="undefined"!=typeof tinymce?tinymce.i.o():document.getElementsByTagName("textarea")[0];if("none"==b.style.display)console.log("insert into tinymce"),tinymce.i.execCommand("mceInsertContent",!1,"some text");else if(console.log("insert into textarea at caret pos"),b.selectionStart||0===b.selectionStart){var d=b.selectionStart,e=b.scrollTop;b.value=b.value.substring(0,d)+a+b.value.substring(b.selectionEnd,b.value.length);b.focus();b.selectionStart=d+a.length;b.selectionEnd=
d+a.length;b.scrollTop=e}else console.log("no browser support, IE?"),alert("Please switch to Visual editing mode first")},showForm:function(a,b){function d(){function e(a,b){var c=a[0],f=document.createDocumentFragment();f.appendChild(g("h3",null,c.title));var d=c.abstractNote;if(d&&(d=d.trim(),0<d.length)){var c=d.split("\n"),k="sixteen columns";500<d.length&&(k+=" newspaper-cols");d=Q("div",{"class":k});for(k=0;k<c.length;k++)0<d.childNodes.length&&d.appendChild(Q("div",{"class":"br"})),d.appendChild(document.createTextNode(c[k]));
f.appendChild(d);b.appendChild(f)}}function d(c,e){zDom=(new DOMParser).parseFromString(c,"application/xml");for(var f=zDom.getElementsByTagNameNS("http://zotero.org/ns/api","year")[0],k=zDom.getElementsByTagNameNS("http://zotero.org/ns/api","creatorSummary")[0],f=g("div",null,["(",g("a",{"data-href":"#"+("z"+a+"-"+b),"class":"zrefcopier-short-ref"},[k?k.firstChild:"(unknown author)"," ",f?f.firstChild:"20xx"]),")"]);f.firstChild;)e.appendChild(f.firstChild)}function s(c,f){function e(a,b){b(a);for(var c=
a.firstChild;c;){var f=c.nextSibling;e(c,b);c=f}}var d=(new DOMParser).parseFromString(c,"text/html").querySelector("div.csl-entry");g("a",{id:"z"+a+"-"+b,"class":"zreader-anchor"},g("span",{"class":"zreader-hidden-anchor"},"*"));e(d,function(a){if("#text"==a.nodeName){var b=a.nodeValue,c=/(.*?doi:)(\S+)(.*)/.exec(b);if(c){var f=document.createDocumentFragment();f.appendChild(document.createTextNode(c[1]));f.appendChild(Q("a",{href:"http://dx.doi.org/"+c[2],xtarget:"_blank"},c[2]));0<c[3].length&&
f.appendChild(document.createTextNode(c[3]));a.parentNode.replaceChild(f,a)}if(c=/(.*?)(https?:\/\/\S+)(.*)/.exec(b))f=document.createDocumentFragment(),f.appendChild(document.createTextNode(c[1])),f.appendChild(Q("a",{href:c[2],xtarget:"_blank"},c[2])),0<c[3].length&&f.appendChild(document.createTextNode(c[3])),a.parentNode.replaceChild(f,a)}});var k=g("a",{href:"http://ourcomments.org/cgi-bin/zformat.php?"+["zk\x3d"+A,"zgi\x3d"+B,"f\x3dhttp://ourcomments.org/psych/zfsp.html"].join("\x26")},"in"+
String.fromCharCode(160)+"Zotero"),k=g("span",null,[" (",k,")"]);for(d.appendChild(k);f.firstChild;)f.removeChild(f.firstChild);for(d=document.importNode(d,!0);d.firstChild;)f.appendChild(d.firstChild)}var c=document.getElementById("zrefcopier-bg");if(c)c.style.display="flex";else{var p=function(a,c){console.log("updateOutput",a,c);if(a)if(c)C.push(a);else for(var b=0;b<C.length;b++)C[b]===a&&C.splice(b,1);if(D){for(;k.firstChild;)k.removeChild(k.firstChild);for(b=0;b<C.length;b++)switch(k.appendChild(g("hr")),
C[b]){case "citation":for(k.appendChild(l);l.firstChild;)l.removeChild(l.firstChild);if(!I){if(!A)debugger;I=new M(G(D)+"items/"+A+"?format\x3dbib\x26style\x3dapa",l,null,s)}R(I);break;case "abstract":for(k.appendChild(z);z.firstChild;)z.removeChild(z.firstChild);if(!T){var f=D.item(A);T=new M(f,z,e)}R(T);break;case "short":for(k.appendChild(w);w.firstChild;)w.removeChild(w.firstChild);u||(u=new M(H(D,A),w,null,d));R(u);break;default:console.log("bad value in outputList",C)}k.appendChild(g("hr"))}},
g=Q,c=g("div",{id:"zrefcopier-bg"});document.body.appendChild(c);var h=c.style;h.position="fixed";h.top="0";h.left="0";h.width="100%";h.height="100%";h.background="rgba(30, 30, 30, 0.7)";h.zIndex="100";h.cursor="wait";var x=g("a",{id:"zrefcopier-closeform",title:"Close"},String.fromCharCode(10006)),F=g("div",{id:"zrefcopier-header"},[g("span",null,"From here you can copy and paste with formatting to Wordpress, LibreOffice etc. "),g("a",{href:"javascript:alert('more info is coming soon')"},"More info")]),
f,O;b||(f=g("input",{id:"zrefcopier-url",type:"text"}),O=g("label",null,["Enter URL of reference in Zotero",f]));g("div");var k=g("div",{id:"zrefcopier-view",contenteditable:"false"}),V=g("div",{id:"zrefcopier-view-container"},[k]),K=g("div",{id:"zrefcopier-inner-controls"}),P=g("button",{title:"Insert in edited post/page"},"Insert"),q=g("div",{id:"zrefcopier-selectall",xtitle:"Select all text"},"Select all text");V.appendChild(q);var $=g("div",{id:"zrefcopier-outer-controls"},[K,P]),W=g("div",{id:"zrefcopier-copy"},
"Now press Control-C to copy to clipboard"),F=g("div",{id:"zrefcopier-form"},[F,O,$,V,x,W]);O=g("div",{id:"zrefcopier-form-container"},F);c.appendChild(O);h.cursor=null;f&&f.focus();x.addEventListener("click",function(){y()});var B=a,A="TI6C7MH6",A="EZBTRX9P",A=b,D;B&&(D=new v(!0,B));B?(q.style.display="inline-block",P.style.display="none"):(q.style.display="none",P.style.display="inline-block");var C=[],h=g("input",{id:"zrefcopier-lnk-chk",type:"checkbox",checked:"checked"}),x=g("label",{title:""},
[h,"Short referens"]);K.appendChild(x);var w=g("p");h.addEventListener("click",function(){p("short",this.checked)});h=g("input",{id:"zrefcopier-cit-chk",type:"checkbox",checked:"checked"});x=g("label",{title:""},[h,"Referens"]);K.appendChild(x);var l=g("blockquote",{"class":"zrefcopier-referens",id:"z"+a+"-"+b});h.addEventListener("click",function(){p("citation",this.checked)});h=g("input",{id:"zrefcopier-abs-chk",type:"checkbox"});x=g("label",{title:""},[h,"Abstract"]);K.appendChild(x);var z=g("blockquote",
{id:"zrefcopier-abstract"});h.addEventListener("click",function(){p("abstract",this.checked)});p("short",!0);p("citation",!0);h.focus();K=function(){var a=null;return function(){var b=f.value;if(b!=a){a=b;for(delete l.dataset.c;l.firstChild;)l.removeChild(l.firstChild);for(delete z.dataset.c;z.firstChild;)z.removeChild(z.firstChild);for(delete w.dataset.c;w.firstChild;)w.removeChild(w.firstChild);A=A||(!0)[2];B||(B="56508");D=new v(!0,B);p()}}}();f&&(f.addEventListener("change",K),f.addEventListener("keyup",
K));P.addEventListener("click",function(){var a=k.cloneNode(!0).innerHTML;ZReaderRefCopier.l(a);c.style.display="none"});q.addEventListener("click",function(){var a=document.createRange();a.selectNodeContents(k);window.getSelection().removeAllRanges();window.getSelection().addRange(a)});k.addEventListener("focus",function(){var a=document.createRange();a.selectNode(k);window.getSelection().removeAllRanges();window.getSelection().addRange(a)});var y=function(){c.style.display="none"};document.addEventListener("keydown",
function(a){a.stopPropagation();W.style.display="none";27==a.keyCode&&y()});c.addEventListener("click",function(a){a.stopPropagation();y()});F.addEventListener("click",function(a){a.stopPropagation();a.stopImmediatePropagation()});c.addEventListener("focusout",function(a){a.stopPropagation();var b=a.relatedTarget;if(b){a=a.target;var f=!1;for(n=0;!f&&b&&30>n++;)b=b.parentNode,f=b===c;f||a&&a.focus()}})}var T,I,u}var e=document.getElementById("zrefcopier-css");if(!e){if(e=document.createElement("link"),
document.head.appendChild(e),e.setAttribute("id","zrefcopier-css"),e.setAttribute("rel","stylesheet"),e.setAttribute("type","text/css"),e.setAttribute("href","http://dl.dropboxusercontent.com/u/848981/it/z/css/edit.css"),e.onload=function(){M&&Q&&d()},M&&Q)return}else if(M&&Q){d();return}e=document.createElement("script");document.head.appendChild(e);e.setAttribute("id","zrefcopier-js");e.onload=function(){d()};e.src="http://dl.dropboxusercontent.com/u/848981/it/z/js/zreader.js";console.log("waiting for zreader.js ...")}};(function(){function a(){var a;a="";var b=window.getSelection().toString();0<b.length&&(a='"'+b+'"');if(b=document.getElementById("tag-container"))for(var b=b.querySelectorAll(".checked-tag"),c=0;c<b.length;c++)0<a.length&&(a+=" "),a+='"'+b[c].firstChild.nodeValue+'"';var b=document.getElementById("glass2"),c=document.getElementById("glass-cont"),d="javascript:alert('Select text or tags to search')";a&&0<a.length?(d=t.f+"?q\x3d"+encodeURIComponent(a),c.classList.add("glass-searchable")):c.classList.remove("glass-searchable");
b.setAttribute("href",d)}function b(a,b){function d(){for(var a=document.getElementById("output-attachments").querySelectorAll("img"),b=/https?:\/\/[^/]+\//,c=0,f=a.length;c<f;c++){var e=a[c],g=e.parentNode.getAttribute("href"),k=b.exec(g)[0]+"favicon.ico";RegExp(/^Full ?text$/).test(e.parentNode.textContent)?k="https://dl.dropboxusercontent.com/u/848981/it/z/img/fulltext.svg":/nih.gov\//.test(k)?k="http://www.ncbi.nlm.nih.gov/favicon.ico":/dropboxusercontent/.test(k)?k="http://www.zotero.org/favicon.ico":
g.substr(0,t.length)===t&&(k="http://dl.dropboxusercontent.com/u/848981/it/z/favicon.ico");a[c].setAttribute("src",k)}}function e(a,b){return x?B[1]+a+B[2]+b+B[3]:t+"?zgi\x3d"+a+"\x26zk\x3d"+b}function r(){return c("img",{width:"16",height:"16"})}var h=window.location.href,q=/[^?]*/.exec(h),t=q[0];console.log(q[0]);console.log(h);var x=q[0]===h;if(x){var B=RegExp("(.*)"+php_zgi+"(.*)"+php_zk+"(.*)").exec(h),x=B;console.log("m2",B)}console.log(e("AAAAAA","BBBBBB"));"complete"==document.readyState?
setTimeout(d,1):window.onload=d;for(var A=c("div",{"class":"inner-container"}),h=c("div",{"class":"inner-container"}),D=c("div",{"class":"inner-container"}),C=c("div",{"class":"inner-container"}),w=0;w<a.length;w++){var l=a[w],z;for(z in l);switch(l.itemType){case "attachment":switch(l.linkMode){case "linked_url":var q=l.url,y=l.title,l="color-other";/facebook.com/i.test(q)?l="color-facebook":/full/i.test(y)?l="color-full":/annot/i.test(y)?l="color-annotation":/diigo/i.test(y)?l="color-annotation":
/nih.gov/i.test(q)?(l="color-pubmed",s||(s=q)):/books.google./i.test(q)&&(l="color-book",s||(s=q));h.appendChild(c("a",{"class":"attachment linked-url "+l,href:q,xtarget:"_blank"},[r(),c("span",null,y)]));break;case "imported_url":q=l.url;y=l.title;h.appendChild(c("div",{"class":"attachment linked-url"},[c("i",null,y),", imported web page, can be accessed from desktop Zotero."]));break;case "imported_file":q=l.url;y=l.title;h.appendChild(c("div",{"class":"imported-file attachment"},[c("i",null,y),
", attached file, can be accessed from desktop Zotero."]));break;default:console.log("unhandled linkMode:",l)}break;case "note":q=l.note;l=c("div",{"class":"note attachment"},null);l.innerHTML=q;D.appendChild(l);break;default:console.log("unhandled child:",l)}}if("undefined"!==typeof php_parent_zid){q=php_parent_zid;z=php_parent_zgrp;var F=e(z,q),I=H(g,q),y=q;(function(){var a=c("span",null,y),b=c("a",{href:F,"class":"related-item attachment color-related"},[r(),a]);A.appendChild(b);U(I,null,null,
function(b){b=(new DOMParser).parseFromString(b,"text/html").querySelector("title").firstChild.nodeValue;a.replaceChild(document.createTextNode(b),a.firstChild)})})()}if(p&&0<Object.keys(p).length){l=/^https?:\/\/zotero.org\/groups\/([0-9]+)\/items\/(.*)$/;c("div",{"class":"related-container"});for(var u in p){var L=p["dc:relation"];"string"==typeof L&&(L=[L]);for(var w=0,Z=L.length;w<Z;w++)q=l.exec(L[w]),z=q[1],q=q[2],F=e(z,q),I=H(g,q),y=q,function(){var a=c("span",null,y),b=c("a",{href:F,"class":"related-item attachment color-related"},
[r(),a]);C.appendChild(b);U(I,null,null,function(b){b=(new DOMParser).parseFromString(b,"text/html").querySelector("title").firstChild.nodeValue;a.replaceChild(document.createTextNode(b),a.firstChild)})}()}}if(0<A.children.length+h.children.length+D.children.length+C.children.length&&(0<A.children.length&&(u=c("div",{"class":"outer-container",id:"links-container"}),u.appendChild(c("div",{"class":"etc-label-div"},c("span",{"class":"etc-label"},"Owner parent"))),u.appendChild(A),b.appendChild(u)),0<
h.children.length&&(u=c("div",{"class":"outer-container",id:"links-container"}),u.appendChild(c("div",{"class":"etc-label-div"},c("span",{"class":"etc-label"},"Links"))),u.appendChild(h),b.appendChild(u)),0<D.children.length&&(u=c("div",{"class":"outer-container",id:"notes-container"}),u.appendChild(c("div",{"class":"etc-label-div"},c("span",{"class":"etc-label"},"Notes"))),u.appendChild(D),b.appendChild(u)),0<C.children.length)){u=c("div",{"class":"outer-container",id:"related-container"});var h=
c("summary",null,"note"),S=c("span",{style:"display:none"},"Due to a bug in Zotero relations are not always displayed both ways. So the relation you see here may not be seen on related documents below. (Hm, it might be gone now. No, it is not!)");h.addEventListener("click",function(){S.style.display="none"==S.style.display?"inline-block":"none"});u.appendChild(c("div",{"class":"etc-label-div"},[c("span",{"class":"etc-label"},"Related"),c("details",{id:"zot-rel-problems"},[h,S])]));u.appendChild(C);
b.appendChild(u)}}function d(){console.log("getLibFromXml -----------------------------");document.getElementById("libinfolink").addEventListener("click",function(a){a.preventDefault();a.stopPropagation();console.log("clicked");a=document.querySelector("#libinfo");"block"===a.style.display?a.style.display="none":"none"===a.style.display?a.style.display="block":Y(a)})}function e(a,b){if("undefined"===typeof ZReaderRefCopier){var d;if(RegExp(/\.php\?/).exec(location.href)){var e=document.querySelector("base");
e?d=e.href:function(){var a=document.querySelector("#zformat-js");d=RegExp(/(.*?\/)js\/[^\/]*$/).exec(a.src)[1]}()}else d=location.protocol+"//"+location.host+location.pathname,d=d.replace(/\/zformat.html.*$/,"/");e=c("script",{id:"ourcomments-edit-js"});document.head.appendChild(e);e.onload=function(){ZReaderRefCopier.showForm(a,b)};e.src=d+"js/edit.js"}else ZReaderRefCopier.showForm(a,b)}function r(){console.log("requestChildren ----------------------------");var a=document.getElementById("output-attachments");
if("undefined"===typeof php_parent_zid){console.log("php_parent_zid \x3d\x3d\x3d undefined");var c=g.children(x);U(c,a,b,d)}else console.log("php_parent_zid !\x3d\x3d undefined"),b([],a)}var t=new function(a){if(1<a.length)for(var b=0,c=a.substr(1).split("\x26");b<c.length;b++)a=c[b].split("\x3d"),this[decodeURIComponent(a[0])]=1<a.length?decodeURIComponent(a[1]):""}(window.location.search);t.f="http://OurComments.org/psych/zfsp.html";var s,c=Q,p=null;"undefined"!==typeof php_relations&&(p=php_relations);
var g,h=php_zgi,x=php_zk,F=t.z;(function(){function b(){if(F){var c=/https?:\/\/www.zotero.org\/groups\/(.*?)\/items\/itemKey\/([^/]*)/.exec(F);x=x||c[2]}g=new v(!0,h);document.getElementById("output").style.display="block";document.getElementById("glass2").addEventListener("touchstart",function(a){a.target.p()});document.body.addEventListener("mouseup",function(){a()});document.body.addEventListener("touchend",function(){a()});document.getElementById("cite").addEventListener("click",function(a){a.stopPropagation();
a.stopImmediatePropagation();a.preventDefault();e(h,x)});for(var c=document.getElementById("output-details").querySelectorAll(".tag [type\x3dcheckbox]"),d=0,f;f=c[d++];)f.addEventListener("click",function(b){b.stopPropagation();this.checked?(this.parentNode.classList.add("checked-tag"),this.style.display="inline-block"):(this.style.display="none",this.parentNode.classList.remove("checked-tag"));a()});r()}switch(document.readyState){case "loading":document.addEventListener("DOMContentLoaded",function(){b()});
break;case "interactive":case "complete":b();break;default:debugger}})()})();})();