/* Copyright 2014 lennart.borgman@gmail.com */ (function(){(function(){function s(c){for(var b in r)if(c==r[b])return b}function g(c,b,d){function f(b){"string"==typeof b?a.appendChild(document.createTextNode(b)):a.appendChild(b)}var a=document.createElement(c);if(d)if(d.length&&"string"!=typeof d)for(c=0;c<d.length;c++)f(d[c]);else f(d);for(var e in b)a.setAttribute(e,b[e]);return a}function t(c){return(new DOMParser).parseFromString(c,"text/xml").querySelectorAll("content")}function k(c,b){return g("div",{"class":"drow"},[g("span",{"class":"dt"},c),g("span",
{"class":"dd"},b)])}function u(c){c=t(c);1!=c.length&&console.log("main contents length !\x3d 1");c=JSON.parse(c[0].firstChild.nodeValue);var b=document.createDocumentFragment();document.querySelector("#zotlink a").setAttribute("href",m.z);var d=c.url;b.appendChild(k("Title",g("a",{href:d,id:"ref-title"},c.title)));var f="";if(d=c.creators){for(var a=0;a<d.length;a++){var e=d[a].b,h=d[a].c;if(h||e)if(h=h.trim(),e=e.trim(),0<h.length||0<e.length)0<f.length&&(f+=", "),f+=e+" "+h}f=f.trim();0<f.length&&
b.appendChild(k("Authors",f))}if(a=c.abstractNote)if(a=a.trim(),0<a.length){f=a.split("\n");console.log("abs length",a.length);d="sixteen columns";500<a.length&&(d+=" newspaper-cols");d=g("div",{"class":d});for(a=0;a<f.length;a++)0<d.childNodes.length&&d.appendChild(g("div",{"class":"br"})),d.appendChild(document.createTextNode(f[a]));b.appendChild(k("Abstract",d))}(a=c.date)&&(a=a.trim());a&&0!=a.length||(a=c.accessDate+" (accessed)");a&&(a=", "+a);f=v[c.itemType]||c.itemType;e=c.publicationTitle||
c.websiteTitle||c.publisher;if(!e){if(d=c.url)d=/https?:\/\/[^/]*/.exec(d),e=g("a",{href:d[0]},d[0]);e||(e="Unknown source")}b.appendChild(k(f,[e,a]));d=c.tags;if(0<d.length){f=g("div",{id:"tag-container"});e=[];h=[];for(a=0;a<d.length;a++){var w=d[a];h[a]=g("input",{type:"checkbox",style:"display:none"});h[a].addEventListener("click",function(a){a.stopPropagation();this.checked?(this.parentNode.classList.add("checked-tag"),this.style.display="inline-block"):(this.style.display="none",this.parentNode.classList.remove("checked-tag"));
a=document.getElementById("tag-container").querySelectorAll(".checked-tag");document.getElementById("glass-cont").style.opacity=0<a.length?1:null});e[a]=g("label",{"class":"tag"},[w.f,h[a]]);f.appendChild(e[a])}a=g("a",{id:"search-tags",target:"_blank"},"Search for tags");a.addEventListener("click",function(){for(var a=document.getElementById("tag-container").querySelectorAll(".checked-tag"),b="",c=0;c<a.length;c++)0<b.length&&(b+=" "),b+='"'+a[c].firstChild.nodeValue+'"';console.log(b);this.setAttribute("href",
m.a+"?q\x3d"+encodeURIComponent(b))});a=g("div",{id:"search-tags-div",style:"display:none"},a);b.appendChild(k("Tags",[f,a]))}a=g("span",{id:"cite-div",title:"Show citation"},"►");a.addEventListener("click",function(){y()});b.appendChild(k("How to Cite",a));a=document.getElementById("output");a.replaceChild(b,a.firstChild);p=c.relations}function z(c){var b=t(c);c=document.createDocumentFragment();for(var d=document.createDocumentFragment(),f=document.createDocumentFragment(),a=0;a<b.length;a++){var e=
JSON.parse(b[a].firstChild.nodeValue);switch(e.itemType){case "attachment":switch(e.linkMode){case "linked_url":var h=e.title;c.appendChild(g("a",{href:e.url,"class":"linked-url"},h));break;default:console.log("unhandled linkMode:",e)}break;case "note":h=e.note;e=g("div",{"class":"note"},null);e.innerHTML=h;d.appendChild(e);break;default:console.log("unhandled child:",e)}}if(p){var k=[],l=[],n;for(n in p){var e=/zotero.org\/groups\/(.*?)\/items\/([^/]*)/.exec(p[n]),h=e[1],b=e[2],e=/[^?]*/.exec(window.location.href),
e=e[0]+"?z\x3dhttps://www.zotero.org/groups/"+s(h)+"/items/itemKey/"+b,m="https://api.zotero.org/groups/"+h+"/items/"+b,h=b;k[a]=g("a",{href:e,"class":"related-item"},h);l[a]=new XMLHttpRequest;l[a].onload=function(){console.log("xhr callback ",l[a].status);if(200<=l[a].status&&400>l[a].status){var b=l[a].responseText;zDom=(new DOMParser).parseFromString(b,"text/xml");b=zDom.querySelector("title").firstChild.nodeValue;k[a].replaceChild(document.createTextNode(b),k[a].firstChild)}else console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+
l[a].status.toString())};l[a].open("GET",m,!0);l[a].setRequestHeader("Zotero-API-Version","2");l[a].send();f.appendChild(k[a])}}0<c.children.length+d.children.length+f.children.length&&(n=document.getElementById("output-attachments"),n.appendChild(g("div",{id:"etc-label"},"Links and Notes:")),n.appendChild(c),n.appendChild(d),n.appendChild(f))}function A(c){function b(c,a){a(c);for(var e=c.firstChild;e;){var d=e.nextSibling;b(e,a);e=d}}zDom=(new DOMParser).parseFromString(c,"text/xml");c=zDom.querySelector("div.csl-entry");
b(c,function(b){if("#text"==b.nodeName){var a=/(.*?doi:)(\S+)(.*)/.exec(b.nodeValue);if(a){var c=document.createDocumentFragment();c.appendChild(document.createTextNode(a[1]));c.appendChild(g("a",{href:"http://dx.doi.org/"+a[2]},a[2]));0<a[3].length&&c.appendChild(document.createTextNode(a[3]));b.parentNode.replaceChild(c,b)}}});var d=document.getElementById("cite-div");d.parentNode.replaceChild(c,d)}function B(){var c=q+"?format\x3datom\x26content\x3djson",b=new XMLHttpRequest;b.onload=function(){console.log("xhr callback ",
b.status);200<=b.status&&400>b.status?(u(b.responseText),C()):console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+b.status.toString())};b.open("GET",c,!0);b.setRequestHeader("Zotero-API-Version","2");b.send();c=document.getElementById("output");c.replaceChild(g("div",null,g("span",null,"Waiting for main content from Zotero...")),c.firstChild)}function C(){var c=q+"/children?format\x3datom\x26content\x3djson",b=new XMLHttpRequest;b.onload=function(){console.log("xhr callback ",
b.status);200<=b.status&&400>b.status?z(b.responseText):console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+b.status.toString())};b.open("GET",c,!0);b.setRequestHeader("Zotero-API-Version","2");b.send()}function y(){var c=q+"?format\x3dbib\x26style\x3dapa",b=new XMLHttpRequest;b.onload=function(){console.log("xhr callback ",b.status);200<=b.status&&400>b.status?A(b.responseText):console.log("Couldn't read the requested file,\x3cbr /\x3estatus \x3d "+b.status.toString())};b.open("GET",
c,!0);b.setRequestHeader("Zotero-API-Version","2");b.send();document.getElementById("cite-div").appendChild(document.createTextNode("Waiting for citation from Zotero ..."))}var r={from_some_psychologists:56508,minding_my_mitochondria_terry_wahls:136570},m=function(){var c=window.location.search.substr(1),b;if(null!=c&&""!=c){b={};for(var c=c.split("\x26"),d=0;d<c.length;d++){var f=c[d].split("\x3d");b[f[0]]=f[1]}}else b={};return b}(),p=null,v={book:"Book",journalArticle:"Journal Article",newspaperArticle:"News Article",
webpage:"Web Page"},q;window.onload=function(){par="parameters: "+m.toString();var c=m.d,b=/https?:\/\/www.zotero.org\/groups\/(.*?)\/items\/itemKey\/([^/]*)/.exec(m.z),d=b[1],b=b[2],f=r[d]||d;c||(d.match("^[0-9]*$")&&(d=s(d)),c=d.split("_").join(" "),document.getElementById("lib-title").appendChild(document.createTextNode(c)),document.getElementById("output").style.display="block");document.getElementById("glass2").addEventListener("mousedown",function(){var a="",b=window.getSelection().toString();
0<b.length&&(a='"'+b+'"');if(b=document.getElementById("tag-container"))for(var b=b.querySelectorAll(".checked-tag"),c=0;c<b.length;c++)0<a.length&&(a+=" "),a+='"'+b[c].firstChild.nodeValue+'"';console.log(a);this.setAttribute("href",m.a+"?q\x3d"+encodeURIComponent(a))});document.getElementById("glass2").addEventListener("touchstart",function(a){a.target.e()});document.body.addEventListener("mouseup",function(){document.getElementById("glass-cont").style.opacity=0<window.getSelection().toString().length?
1:null});q="https://api.zotero.org/groups/"+f+"/items/"+b;B()}})();})();